### PR TITLE
Add initial draft of LRZ post

### PR DESCRIPTION
**Pull request by javdg**
This is the initial draft version of a LRZ contribution to the blog.
I will add pictures early next week (they may or may not involve a certain machine and stickers...).
@tgamblin please let me know if this is what you had in mind or if another focus (e.g. more technical details) and/or longer format is prefered. Thanks!

### CODE REVIEW

**Comment by tgamblin** [comment]
Thanks @javdg!  I'll get a chance to review this sometime this week!

**Comment by hauten** [comment]
Hi @javdg - @tgamblin asked me to look at this. The excerpt cuts off at 25 words on /blog (see screen shot), so can you please shorten it?

Also, the blog page doesn't display author from line 5, so please add your name at the bottom of the post on a new line, like:
_-- Johannes Albert-von der Gönna, Leibniz Supercomputing Centre_

(You're the 1st guest post, so maybe we'll adjust the display differently in the future...)
Thanks for contributing.
lrz screen shot

**Comment by javdg** [comment]
Thanks for the review, @hauten 
I made some changes which hopefully address your suggestions.

**Comment by hauten** [comment]
Thanks @javdg! @tgamblin, this is ready to merge

**Review by tgamblin — APPROVED** [review]

**Comment by tgamblin** [comment]
@hauteb: awesome — want to tweet it once the build finishes and it shows up on spack.io?

**Pull request merged**
